### ISSUE TITLE
Typescript error - Cannot find module './devtoolsMidleware'

### ISSUE THREAD

**Issue by gcox** [redux-zero/redux-zero#140]
**`version 4.15.1`**

When `redux-zero` is installed, the `devtoolsMidleware.d.ts` file is not included which leads to an error since that file imported by `devtoolsMiddleware.d.ts`

Is there any particular reason the devtools typings were implemented this way? I'm no expert on typings so I'm sure I'm just missing something.

<img width="790" alt="screen shot 2018-12-20 at 9 14 17 am" src="https://user-images.githubusercontent.com/251512/50289716-a20d3e00-0437-11e9-8258-5d293b2eb92c.png">

<img width="320" alt="screen shot 2018-12-20 at 9 14 37 am" src="https://user-images.githubusercontent.com/251512/50289737-ae919680-0437-11e9-87ef-34a5f4bf215a.png">

**Comment by gebeto** [comment]
It is because there are naming conflicts in sources, `devtoolsMiddleware.ts` imports `devtoolsMiddleware.d.ts`, it is bad

@matheusml need to rename `devtoolsMiddleware.d.ts` to something like `devtoolsMiddlewareInterfaces.ts` or move all interfaces from `devtoolsMiddleware.d.ts` into `devtoolsMiddleware.ts` file

or move `devtoolsMiddleware.d.ts` to `interfaces` folder

**Comment by gebeto** [comment]
## Result

![screen shot 2019-01-02 at 3 12 23 pm](https://user-images.githubusercontent.com/13422799/50593378-d43f8680-0ea0-11e9-956d-fe9510583574.png)

**Comment by matheusml** [comment]
Thanks for that @gebeto. I would gladly accept this PR.

**Comment by gebeto** [comment]
@matheusml I've add it to #142, can you check that PR?
